### PR TITLE
Complete transition from tuples to `Result<>`

### PR DESCRIPTION
**Pull request by OmerFlame**
This is not yet finished, we need proper documentation terminology for the new changes, both for the `completionHandler` type functions as well as the `async` wrappers.

### CODE REVIEW

**Comment by OmerFlame** [comment]
@WilhelmOks since you are not responding, I am going to immediately merge this change into main and create a new major release.

**Comment by WilhelmOks** [comment]
Sry, this week was quite busy for me.
I'm curious to see the changes. 👍

**Comment by OmerFlame** [comment]
No worries! I am really happy how this library is turning out with some feedback.

**Comment by WilhelmOks** [comment]
Changes are looking good!
I've already adopted the changes and it makes it very easy for me to use the API calls now because I use throwing functions and I just call .get() on the Result value and thats it.

**Pull request merged**
